- defaults:
    link:
      create: true
      relink: true

- link:
    ~/.gitignore: git/ignore
    ~/.gitconfig: git/config
    ~/.gitconfig.canonical: git/config.canonical

    ~/.hushlogin:

    ~/.config/nano/nanorc: nano/nanorc 
    ~/.config/nano/syntax-highlighting: nano/syntax-highlighting