- defaults:
    link:
      create: true
      relink: true
    aptget:
      upgrade: true

- link:
    ~/.gitignore: git/ignore
    ~/.gitconfig: git/config
    ~/.gitconfig.canonical: git/config.canonical

    ~/.hushlogin:

    ~/.config/nano:
    ~/.config/htop:
    ~/.config/less:
    
    ~/.nvm:
    ~/.profile: shell/profile
    ~/.profile.d: shell/profile.d
    ~/.functions.d: shell/functions.d

- sudo:
    - link:
        /etc/apt/preferences.d/disallow-games.pref: system/apt/preferences.d/disallow-games.pref
        /etc/apt/preferences.d/disallow-grub.pref: system/apt/preferences.d/disallow-grub.pref

    - snap:

        jq:
        yq:

        # instant messaging applications
        discord:
        caprine:
        mattermost-desktop:
        telegram-desktop:

    - aptget:
        # shell utilities
        fzf:

        # sysadmin utilities
        procinfo:
        hdparm:

        # android tools
        adb:
        fastboot:

        python-is-python3:
        emacs:
