- defaults:
    link:
      create: true
      relink: true
    aptget:
      upgrade: true

- link:
    ~/.gitignore: git/ignore
    ~/.gitconfig: git/config
    ~/.gitconfig.canonical: git/config.canonical

    ~/.hushlogin:

    ~/.config/nano/nanorc: nano/nanorc 
    ~/.config/nano/syntax-highlighting: nano/syntax-highlighting

    ~/.config/htop/htoprc: htop/htoprc

- sudo:
    - snap:

        jq:
        yq:

        # instant messaging applications
        discord:
        caprine:
        mattermost-desktop:
        telegram-desktop:

    - aptget:
        python-is-python3:
        emacs:
