- defaults:
    link:
      create: true
      relink: true
    aptget:
      upgrade: true

- link:
    ~/.gitignore: git/ignore
    ~/.gitconfig: git/config
    ~/.gitconfig.canonical: git/config.canonical

    ~/.hushlogin:

    ~/.config/nano:
    ~/.config/htop:
    ~/.config/less:
    
    ~/.profile: shell/profile
    ~/.profile.d: shell/profile.d
    ~/.functions.d: shell/functions.d

    ~/.zshrc: shell/zsh/zshrc.zsh

    ~/.ansiweatherrc:


- git:
    ~/.fonts/nerd-fonts:
        description: Nerd Fonts
        url: https://github.com/ryanoasis/nerd-fonts.git
        method: clone-or-pull

    ~/.nvm:
        description: Node Version Manager
        url: https://github.com/nvm-sh/nvm.git
        branch: v0.39.4
        method: clone-or-pull
    ~/.zplug:
        description: Zsh Plugin Manager
        url: https://github.com/zplug/zplug.git
        branch: 2.4.2
        method: clone-or-pull

- sudo:
    - link:
        /etc/apt/preferences.d/disallow-games.pref: system/apt/preferences.d/disallow-games.pref
        /etc/apt/preferences.d/disallow-grub.pref: system/apt/preferences.d/disallow-grub.pref

    - snap:
        # syseng
        juju:
        lxd:
        dotrun:

        # Canonical tools
        snapcraft:
            classic: true
        charmcraft:
            classic: true

        # diagnostic tools
        hotsos:

        # query tools
        jq:
        yq:

        # instant messaging applications
        discord:
        caprine:
        mattermost-desktop:
        telegram-desktop:

    - aptget:
        # shell utilities
        fzf:
        curl:
        fd-find:
        shfmt:
        bat:

        # prefer python3
        python-is-python3:

        # sysadmin utilities
        procinfo:
        hdparm:

        # android tools
        adb:
        fastboot:

        # build dependencies
        build-essential:

        # python build dependencies
        libssl-dev:
        zlib1g-dev:
        libbz2-dev:
        libreadline-dev:
        libsqlite3-dev:
        libncursesw5-dev:
        xz-utils:
        libxml2-dev:
        libxmlsec1-dev:
        libffi-dev:
        liblzma-dev:
        tk-dev:

        # editor
        emacs:
