- defaults:
    link:
      create: true
      relink: true
    aptget:
      upgrade: true

- link:
    ~/.gitignore: git/ignore
    ~/.gitconfig: git/config
    ~/.gitconfig.canonical: git/config.canonical

    ~/.hushlogin:

    ~/.config/nano:
    ~/.config/htop:
    ~/.config/less:

    ~/.profile: shell/profile
    ~/.profile.d: shell/profile.d
    ~/.functions.d: shell/functions.d

- sudo:
    - snap:

        jq:
        yq:

        # instant messaging applications
        discord:
        caprine:
        mattermost-desktop:
        telegram-desktop:

    - aptget:
        # shell utilities
        fzf:

        # sysadmin utilities
        procinfo:


        python-is-python3:
        emacs:
