#!/bin/sh
# shellcheck disable=SC1091
export NPM_PACKAGES="${HOME}/.npm-packages";

append_path "${NPM_PACKAGES}/bin";
append_manpath "${NPM_PACKAGES}/share/man";

#
# Node Version Manager
#
export NVM_DIR="${HOME}/.nvm";

if [ -s "${NVM_DIR}/nvm.sh" ]; then
    . "${NVM_DIR}/nvm.sh";
fi;

if [ -n "${BASH}" ] && [ -s "${NVM_DIR}/bash_completion" ]; then
    . "${NVM_DIR}/bash_completion";
fi;