# L1ARC
options zfs zfs_arc_max=17179869184     # 16 GiB

# L2ARC
options zfs l2arc_write_max=524288000   # 500 * 1024 * 1024

# resilver
options zfs zfs_resilver_min_time_ms=8000
options zfs zfs_resilver_delay=0

# scrubs and scans
options zfs zfs_scan_idle=0
options zfs zfs_scrub_delay=0
options zfs zfs_scan_min_time_ms=5000
options zfs zfs_vdev_scrub_min_active=24
options zfs zfs_vdev_scrub_max_active=64

# sync write
options zfs zfs_vdev_sync_write_min_active=8
options zfs zfs_vdev_sync_write_max_active=32

# sync reads
options zfs zfs_vdev_sync_read_min_active=8
options zfs zfs_vdev_sync_read_max_active=32

# async reads: prefetcher
options zfs zfs_vdev_async_read_min_active=8
options zfs zfs_vdev_async_read_max_active=32

# async write: bulk writes
options zfs zfs_vdev_async_write_min_active=8
options zfs zfs_vdev_async_write_max_active=32

# inflights
options zfs zfs_top_maxinflight=512